# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_genre = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_genre.setGeometry(QtCore.QRect(20, 40, 61, 31))
        self.label_genre.setObjectName("label_genre")
        self.text_genre = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.text_genre.setGeometry(QtCore.QRect(120, 40, 111, 31))
        self.text_genre.setObjectName("text_genre")
        self.label_movietitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_movietitle.setGeometry(QtCore.QRect(20, 110, 61, 31))
        self.label_movietitle.setObjectName("label_movietitle")
        self.label_watch = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_watch.setGeometry(QtCore.QRect(20, 160, 91, 31))
        self.label_watch.setObjectName("label_watch")
        self.label_rating = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_rating.setGeometry(QtCore.QRect(20, 210, 91, 31))
        self.label_rating.setObjectName("label_rating")
        self.text_watch = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.text_watch.setGeometry(QtCore.QRect(120, 160, 111, 31))
        self.text_watch.setObjectName("text_watch")
        self.text_rating = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.text_rating.setGeometry(QtCore.QRect(120, 210, 111, 31))
        self.text_rating.setObjectName("text_rating")
        self.button_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(10, 260, 56, 17))
        self.button_add.setObjectName("button_add")
        self.button_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_search.setGeometry(QtCore.QRect(10, 460, 56, 17))
        self.button_search.setObjectName("button_search")
        self.button_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(250, 40, 56, 17))
        self.button_clear.setObjectName("button_clear")
        self.text_movietitle = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.text_movietitle.setGeometry(QtCore.QRect(120, 110, 111, 31))
        self.text_movietitle.setObjectName("text_movietitle")
        self.button_remove = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_remove.setGeometry(QtCore.QRect(310, 460, 56, 17))
        self.button_remove.setObjectName("button_remove")
        self.label_error = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(10, 290, 461, 131))
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.label_keyword = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_keyword.setGeometry(QtCore.QRect(80, 450, 81, 31))
        self.label_keyword.setObjectName("label_keyword")
        self.text_keyword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.text_keyword.setGeometry(QtCore.QRect(150, 450, 151, 31))
        self.text_keyword.setObjectName("text_keyword")
        self.label_rating10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_rating10.setGeometry(QtCore.QRect(240, 210, 61, 31))
        self.label_rating10.setObjectName("label_rating10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd = QtGui.QAction(parent=MainWindow)
        self.actionAdd.setObjectName("actionAdd")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_genre.setText(_translate("MainWindow", "Genre:"))
        self.label_movietitle.setText(_translate("MainWindow", "Movie Title:"))
        self.label_watch.setText(_translate("MainWindow", "Where to watch:"))
        self.label_rating.setText(_translate("MainWindow", "Rating:"))
        self.button_add.setText(_translate("MainWindow", "Add"))
        self.button_search.setText(_translate("MainWindow", "Search"))
        self.button_clear.setText(_translate("MainWindow", "Clear"))
        self.button_remove.setText(_translate("MainWindow", "Remove"))
        self.label_keyword.setText(_translate("MainWindow", "Keyword:"))
        self.label_rating10.setText(_translate("MainWindow", "/10"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
